### ISSUE TITLE
Loading Spectrum Files

### ISSUE THREAD

**Issue by eduo** [T-Pau/Ready#15]
I wanted to test the new Spectrum machine but I can't seem to be able to launch it. 

What formats are currently recognized for C64 and for Spectrum? D64 + TAP + NIB? TAP + SNA + Z80?

TAP in particular is an extension shared, which the app seems to accept, but then it doesn't seem to properly interpret the contents. I must be missing something...

**Comment by dillof** [comment]
Did you change the Machine to ZX Spectrum? Ready does not yet auto-detect which machine a given file needs.

When you are viewing the library entry with the TAP file, tap the `Machine` button in the upper right corner, tap the computer in the lower left of the popup, select `Sinclair ZX Spectrum +2` (since this is the only Spectrum with joystick support at the moment), and press `Done`.

**Comment by eduo** [comment]
Thanks. I think tapping the computer in the lower left was not doing anything for me but I may be misremembering.
